[project]
name = "bitcoin-tx-proof"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"

requirements = [
    { contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.clarity-bitcoin-lib-v5' },
]

[repl.remote_data]
enabled = true
api_url = "https://api.hiro.so"
initial_height = 581021
